### ISSUE TITLE
Auto adjust focus per filter option

### ISSUE THREAD

**Issue by tlkw79** [rrskybox/Humason#1]
Hi,

Is there an option in Humason for auto-adjust focus per filter instead of autofocus only on one specific filter (ex. Luminance)?

Thanks.

**Comment by rrskybox** [comment]
No option for autofocus for more than one filter. It's not necessary.  Filter offsets are static so it is best to configure them in the Focus Offsets fields of the Filter Wheel Setup in TheSkyX.    AFProfiler is designed to determine these offsets, if you want to use that utility.
