### ISSUE TITLE
Target does not link from HumanOn to Image Forcast Routine

### ISSUE THREAD

**Issue by astromiester1** [rrskybox/Humason#10]
I noticed if you change targets and make a new plan in HumanOn using Lookup, read In or Load target, Image focast does not show the current target but instead the old one. The only way is to use the current target list in image forcast and scroll down till you see the new target and select it. Thought when you call it from Humanon, it would automaticaly pick that one from the list and not show the old one. Just an FYI

Thanks
Dale
(https://user-images.githubusercontent.com/14363854/219176021-1d0d890c-369d-41b9-a18a-e4c1e9783988.jpg)

**Comment by rrskybox** [comment]
Hmmm.  Hadn't really thought about it, but it's a good idea.  I made modifications to Image Planner accordingly.  I also to the opportunity to take out the up/down numeric counters on the target name.  That had been more trouble than it was worth.

Let me know if I broke something else adding this.

**Comment by rrskybox** [comment]
By the way, Milton "Humason" was the observatory assistant who did much of the imaging that Edwin Hubble took credit for, in particular the observations that led to the distances to galaxies and eventually the size of the universe.  Humason was legendary for his ability to stay awake all night while making the slight tweaks needed to keep the Wilson 100 inch targeted.  He once did a 33 hour image over multiple nights in freezing cold.  That image set the record for the largest measured distance to a galaxy at that time.   He should have gotten a Nobel for his work, but Hubble was not one to share credit with anyone, let alone an uncredentialed lackey.  And so it goes...

**Comment by astromiester1** [comment]
Very cool I did not know that.... Interesting....
