### ISSUE TITLE
Focus 2 initiates before telescope turned on

### ISSUE THREAD

**Issue by astromiester1** [rrskybox/Humason#16]
Focus 2 initiates before telescope turned on.

For some reason, focus 2 when selected in devices tab, the sequence trys to focus in open sky where scope is parked before scope connected. Then it fails and connects to scope and trys the sequence without the focus.

**Comment by astromiester1** [comment]
I noticed focus 2 does not listen to user input for star magnitude.. If I tell it to pick mag 6, it picked mag 4. So, I turned off autopick star but still checked subframe and thought the script would find a star in the CLS field of the target but got the behavior stated above. Im going to list that star mag bug behavior in SB forum non the less. Just wanted to give you more info

**Comment by rrskybox** [comment]
The mount should be connected, unparked and tracking before @Focus 2 is run, as near as I can tell from the code.  What is the error you get when @Focus2 fails?  What mount?

Take a look at the TSX manual, starting at page 666 (that's ominous...) for an explanation of how the automatic star selection (actually it's an observing list query) works for @Focus2.  Of note is that the query tries to find a star "near" the current mount pointing location with between 4.5 and 6.5 mag.   The Automatic Star selection "calibration" fields are a means for TSX to calculate an exposure that would produce a decent ADU (i.e. 20K) for running the autofocus procedure.   The magnitude field does not set the magnitude of the autopick'd star, i.e. exposure input field X (selected star mag/mag input field) -> selected star focus exposure.
