### ISSUE TITLE
Humanson 60 sec delay between taking images in script

### ISSUE THREAD

**Issue by astromiester1** [rrskybox/Humason#17]
There seems to be a 60sec delay between taking images in the script...I then try just using Take series in TSX and it works fine no delay. Any idea ?

Thanks
Dale

**Comment by rrskybox** [comment]
This is an odd one.  I haven't seen such a 60 second delay before and can't recreate it now.  I'm also at a loss as to where to look exactly -- I don't know where or for why I might have put in a 60 second delay to be frank.  Could you post your configuration xml file so I could try to replicate your configuration (Humason/SessionControl.xml), and perhaps a log snippet showing the log information around a couple of images that show that delay?

**Comment by astromiester1** [comment]
It might be my computer. I will email you some files shortly.ThanksDaleSent via the Samsung Galaxy S22 5G, an AT&T 5G smartphone
-------- Original message --------From: Rick McAlister ***@***.***> Date: 5/11/23  10:39 PM  (GMT-05:00) To: rrskybox/Humason ***@***.***> Cc: astromiester1 ***@***.***>, Author ***@***.***> Subject: Re: [rrskybox/Humason] Humanson 60 sec delay between taking images in script (Issue #17) 
This is an odd one.  I haven't seen such a 60 second delay before and can't recreate it now.  I'm also at a loss as to where to look exactly -- I don't know where or for why I might have put in a 60 second delay to be frank.  Could you post your configuration xml file so I could try to replicate your configuration (Humason/SessionControl.xml), and perhaps a log snippet showing the log information around a couple of images that show that delay?
