### ISSUE TITLE
Can't run it on Windows 10

### ISSUE THREAD

**Issue by Bioslasher** [rrskybox/Humason#18]
Hi,

I can't run it on Windows 10.  After installation when I try to open it , I can see loading circle for 1-2 seconds and that's all.

I have newest version of Sky X and NET 4.8.0 on my system.

What could be the reason ? 

Best Regards
Bioslasher

**Comment by rrskybox** [comment]
Usually this means that the program is running into an unhandled exception then exiting.  Have you launched TS64 once (and only once) in admin mode?  This is most often the culprit.

**Comment by Bioslasher** [comment]
When I run it in admin mode it works. Thank you !

**Comment by rrskybox** [comment]
That's great but just a note:  Both TSX and Humason must be run at the same privilege level, either Administrator mode or User mode.  Software Bisque recommends strongly that TSX is run in User mode, although it must be run once in Administrator mode to register its interface libraries.  So it may be a good idea to normally run both TSX and Humason in User mode, i.e. not Administrator mode.  Just sayin'.
