### ISSUE TITLE
Humanson does not load with new SKYX build 13638

### ISSUE THREAD

**Issue by astromiester1** [rrskybox/Humason#19]
Not sure if you notices this but I can't launch Humanson when SKYX pro is open..

**Comment by rrskybox** [comment]
When you upgraded to TSX Build 13638, did you run it once in admin mode to re-register the interfaces, close TSX, then run normally (non admin mode)?  This is usually the culprit.

**Comment by astromiester1** [comment]
I will try thisSent via the Samsung Galaxy S22 5G, an AT&T 5G smartphone
-------- Original message --------From: Rick McAlister ***@***.***> Date: 12/12/23  8:19 PM  (GMT-05:00) To: rrskybox/Humason ***@***.***> Cc: astromiester1 ***@***.***>, Author ***@***.***> Subject: Re: [rrskybox/Humason] Humanson does not load with new SKYX build 13638 (Issue #19) 
When you upgraded to TSX Build 13638, did you run it once in admin mode to re-register the interfaces, close TSX, then run normally (non admin mode)?  This is usually the culprit.

**Comment by astromiester1** [comment]
Btw, instead of fixing the issue, sb removed the parameters in skyx for time dusk and dawn in the skyx gui in latest build . Just an fyi. ThanksDaleSent via the Samsung Galaxy S22 5G, an AT&T 5G smartphone
-------- Original message --------From: Rick McAlister ***@***.***> Date: 12/12/23  8:19 PM  (GMT-05:00) To: rrskybox/Humason ***@***.***> Cc: astromiester1 ***@***.***>, Author ***@***.***> Subject: Re: [rrskybox/Humason] Humanson does not load with new SKYX build 13638 (Issue #19) 
When you upgraded to TSX Build 13638, did you run it once in admin mode to re-register the interfaces, close TSX, then run normally (non admin mode)?  This is usually the culprit.

**Comment by rrskybox** [comment]
On removing content on Observing List Advanced tab...  I did notice that.  I suspect that SB finally got tired of answering the same question for ten years.  Or, figured that if that tab had been on their TBD list for that long, then it probably wasn't coming off in the near future and no sense pretending.  Or, recognized that all that functionality could be satisfied with a few simple scripts once they launch the long anticipated Orchestrate revival.  There is no entry in the Change Log for this deletion so no insight there.
