### ISSUE TITLE
Humason does not load when installed Win10 running TSX.

### ISSUE THREAD

**Issue by astromiester1** [rrskybox/Humason#20]
Hi Rick, is there a debugging log I can inspect or upload to you for this to find out why its not loading.. I have no clue why this won't run on my Win10 machine with TSX running first. I am using latest humason build 258 using 64bit version.

I think I may have found the issue.. I tried to rebuild code and debug in VS2019. I noticed I have alot of targets in my Humanson folder say 25 to 30 that I know are good for May.. When I debug, I get the following error..

LRGBRatioBox.Value = (decimal)tPlan.LRGBRatio--->" System.ArgumentOutOfRangeException: 'Value of '0' is not valid for 'Value'. 'Value' should be between 'Minimum' and 'Maximum'.
Parameter name: Value'

Its on line 247 of the SBinitialConfiguration() routine. When I delete all the targets except default.TargetPlan.xml, FlatStack.xml, SequenceSummaries.xml and SessionControl.xml, it runs..

If I copy my targets back in the directory, I get the error above again...

I also, noticed if I only copy the targets wo the files you create it works... I may be good to go now....

Thanks
Dale

**Comment by rrskybox** [comment]
I'd still like to know the root of the problem so I can make Humason a little more robust.  It sounds like the _LRGB Ratio_ value in your target files is either set to 0 or is not there.  I can put in some avoidance code to catch that, but I'd like to know how that is happening.  How are you initially generating these targets?  Is there a XML data element for _LRGB Ratio_ in them?  Thanks.

**Comment by astromiester1** [comment]
I make folders for each day of the month and copy targets back and forth with your xml files to the root. I think its on my end, so I only copy targets now and leave the xml files created on a targetless Humanson folder when first ran. Other than that, im not sure what the issuw is other than me doing things the program wasnt expecting...It works for me now...ThanksDaleSent via the Samsung Galaxy S22 5G, an AT&T 5G smartphone
-------- Original message --------From: Rick McAlister ***@***.***> Date: 5/7/24  10:27 PM  (GMT-05:00) To: rrskybox/Humason ***@***.***> Cc: astromiester1 ***@***.***>, State change ***@***.***> Subject: Re: [rrskybox/Humason] Humason does not load when installed Win10 running TSX. (Issue #20) 
I'd still like to know the root of the problem so I can make Humason a little more robust.  It sounds like the LRGB Ratio value in your target files is either set to 0 or is not there.  I can put in some avoidance code to catch that, but I'd like to know how that is happening.  How are you initially generating these targets?  Is there a XML data element for LRGB Ratio in them?  Thanks.

**Comment by astromiester1** [comment]
I meant names for each month only...Sent via the Samsung Galaxy S22 5G, an AT&T 5G smartphone
-------- Original message --------From: ddidomenico ***@***.***> Date: 5/8/24  7:08 AM  (GMT-05:00) To: rrskybox/Humason ***@***.***>, rrskybox/Humason ***@***.***>, ***@***.*** Cc: State change ***@***.***> Subject: Re: [rrskybox/Humason] Humason does not load when installed Win10 running TSX. (Issue #20) I make folders for each day of the month and copy targets back and forth with your xml files to the root. I think its on my end, so I only copy targets now and leave the xml files created on a targetless Humanson folder when first ran. Other than that, im not sure what the issuw is other than me doing things the program wasnt expecting...It works for me now...ThanksDaleSent via the Samsung Galaxy S22 5G, an AT&T 5G smartphone-------- Original message --------From: Rick McAlister ***@***.***> Date: 5/7/24  10:27 PM  (GMT-05:00) To: rrskybox/Humason ***@***.***> Cc: astromiester1 ***@***.***>, State change ***@***.***> Subject: Re: [rrskybox/Humason] Humason does not load when installed Win10 running TSX. (Issue #20) 
I'd still like to know the root of the problem so I can make Humason a little more robust.  It sounds like the LRGB Ratio value in your target files is either set to 0 or is not there.  I can put in some avoidance code to catch that, but I'd like to know how that is happening.  How are you initially generating these targets?  Is there a XML data element for LRGB Ratio in them?  Thanks.

**Comment by rrskybox** [comment]
I understand -- I do something analogous in another app that scans variable stars.   Seems to me there may be something we can do to help.  What if we created something we'll call Target Groups using Nightshift.  The idea would be to replicate what you're doing by hand:  swap in and out sets of Humason target configuration files from user-named subdirectories into the Humason directory.   When a Target Group is swapped in, it would be active for both Humason and Image Planner without modifying those apps.

I've already got the NightShift code open for the last feature you suggested.  I can add this to the list, let you take it for a run to see if it solves your problem and go from there.

**Comment by astromiester1** [comment]
Sounds like a cool idea....Sent via the Samsung Galaxy S22 5G, an AT&T 5G smartphone
-------- Original message --------From: Rick McAlister ***@***.***> Date: 5/8/24  9:30 AM  (GMT-05:00) To: rrskybox/Humason ***@***.***> Cc: astromiester1 ***@***.***>, State change ***@***.***> Subject: Re: [rrskybox/Humason] Humason does not load when installed Win10 running TSX. (Issue #20) 
I understand -- I do something analogous in another app that scans variable stars.   Seems to me there may be something we can do to help.  What if we created something we'll call Target Groups using Nightshift.  The idea would be to replicate what you're doing by hand:  swap in and out sets of Humason target configuration files from user-named subdirectories into the Humason directory.   When a Target Group is swapped in, it would be active for both Humason and Image Planner without modifying those apps.
I've already got the NightShift code open for the last feature you suggested.  I can add this to the list, let you take it for a run to see if it solves your problem and go from there.
