### ISSUE TITLE
"Observing list hard clear not installed".  Popup error using executable. Won't go away

### ISSUE THREAD

**Issue by astromiester1** [rrskybox/Humason#3]
When I run the program, I get a repeating popup error saying "Observing list hard clear not installed". I see the file in your zip file .dbq. Do I need to install it or copy it somewhere? How do I solve this... Thanks Dale

**Comment by rrskybox** [comment]
That observing list should be automatically installed into the SB Database Query folder for you.  This might be something that I missed when I had to build separate code for TSX32 and TSX64.  Give me a bit to check it out.

**Comment by rrskybox** [comment]
Ok.  The observing list problem should be fixed with the new build -- Humason64Build230.zip.

**Comment by astromiester1** [comment]
Did you upload this yet? I don't see it.. I tried moving the file to the common user database query folder but now when you execute the same error comes up once this time with no gui. Before the message would repeat over and over again when you close it.

**Comment by rrskybox** [comment]
Thought I did, but apparently not.  Should be good to go now.

**Comment by astromiester1** [comment]
I tried the new build. Unzipped and installed. Now, no message and no gui when trying to open. Weird...

**Comment by astromiester1** [comment]
Just to give a heads up. I also, tried to rebuild the latest code and got this Exception error....

(https://user-images.githubusercontent.com/14363854/218316345-98f9cf4b-03ac-49bb-90ec-59e9dcbcd801.jpg)

**Comment by rrskybox** [comment]
Observing List problem apparently resolved.
