### ISSUE TITLE
Just to give a heads up. I also, tried to rebuild the latest code and got this Exception error....

### ISSUE THREAD

**Issue by rrskybox** [rrskybox/Humason#5]
Just to give a heads up. I also, tried to rebuild the latest code and got this Exception error....

(https://user-images.githubusercontent.com/14363854/218316345-98f9cf4b-03ac-49bb-90ec-59e9dcbcd801.jpg)

_Originally posted by @astromiester1 in https://github.com/rrskybox/Humason/issues/3#issuecomment-1427045079_

**Comment by rrskybox** [comment]
Seemed likely that this was something I messed up during full initialization, but a clean install failed to replicate this.  

1. Is there anything unusual about the set up of your Documents folder?  Humason will be trying to create and populate a directory there.
2. Could you rerun and post the call stack and content of the variable "axessXMLFilePath" when this error is thrown?

Thanks.

**Comment by rrskybox** [comment]
Oh, and delete the directory "...Documents/Humason" just in case it got corrupted earlier.

**Comment by astromiester1** [comment]
Deleting the directory and recompiling did the trick.... It works now.... So, I need to read more but I got mostly everything you made populated in nightshift now... I want to be able to take a series of OSC pics in skyx and then have the mount park and stop the guide camera from guiding. Can Humanon do that or close to that? Very impressed with all your work by the way....

Thanks
Dale

**Comment by rrskybox** [comment]
Excellent.  What you describe is pretty much the core of what Humason is designed to do.  There may be a few anomalies as it was designed and tested around my imaging stuff.  I'm sure I've made some assumptions that I shouldn't have, but just let me know and I'll try to get it to work for you.  Just open a new issue and I'll get to it as soon as I can.

**Comment by astromiester1** [comment]
Sweet.... I will let ya know when I see any issues as well... Thanks Again Rick....
