### ISSUE TITLE
Auto Dark Frame Not Needed for a OSC // Plate Solve Fails Script Aborts

### ISSUE THREAD

**Issue by astromiester1** [rrskybox/Humason#7]
Did some testing tonight live... Since, I have a OSC, I don't have dark frames but the interface expects me to use one with my image with autodark. You have a checkbox for the guider but not one for the imager so, if I ignore it, it fails the plate solve cause the image is too dark. Would it be easy for me to disable the dark frame for the imager in the code since I have an OSC.

Here is the HumanOn Script entry when it dies... Just to get it to move forward I put a dark tee shirt over the dew sheild when it asked me too but still did not work. Maybe, I need to set the image link settings different or do you do anything in your plate solver routine.

Sequence Updated
Running diagnostics
Diagnostics success
Loading first session target plan
Waiting until 22:16
Waiting until 22:16
Initializing system
Connecting
Connecting mount
Connecting camera
Connecting guide camera
Connecting focuser
Devices Connected
Checking for new target to clear meridian
New target is clear of meridian
******************* Imaging Target: M81
Disconnecting mount
Initiating coordinate CLS to M81
Unparking mount for CLS, if needed
Initial Slew Completed
CLS Error: Receive time-out. Error = 209.
CLS Failed: Error 209 -- trying again
Unparking mount for CLS, if needed
Initial Slew Completed
CLS Error: The astrometric solution failed. Error = 655.
CLS Failed: 655
Aborting and Closing Down
Parking Mount
Disconnecting all devices
Aborting guiding
Shutting down guider temperature regulation, if any
Disconnecting guider
Disconnecting focuser
Aborting imaging
Turning off camera temperature regulation
Disconnecting camera
Disconnecting mount
All TSX devices disconnected
Abort Completed -- awaiting new orders, Captain

Thanks
Dale

**Comment by rrskybox** [comment]
I found a place where I wasn't using the configured (on the Target tab) calibration for AutoDark when doing a CLS.  I fixed that and gen'd a new build -- Humason64Build231.zip.  I won't have time to test it, but it "should" work now.

**Comment by rrskybox** [comment]
After some thought last night, I decided to both generalize and expand the handling of image reduction choices.  Besides the complexities raised by using an OSC, I also wanted to add Full Reduction as an option (which I've been using a lot recently in other projects).  So, all the reduction choices for imaging, guiding and CLS's have been moved to the Options window.  At the same time, choices for AutoDark have been removed from the Target tab and Guider tab.  You will not have to restart Humason if you only change the reduction choices on the Options tab (I'll get rid of that warning sometime in the future.)

The new rev is Humason64Build232.  I've tested these changes briefly, but I could have always introduced something else.  So it goes.  I left the last build in the hopper just in case.

**Comment by astromiester1** [comment]
I tried the latest 232. This is what I am seeing..

1. Plate solver tab removed. This is a problem because I can't force settings in TSX that I know work. So, Humanon sets it to something and it fails to find a solution and shuts down the script. If I use my settings I can plate solve on same image very quickly but Humanson changes the settings during its run and it fails.

My settings for Humanon is the following:
Options. All reduction off. no rotator, weather or dome.
Using simulator filter wheel. 1 filter called OSC.
Target tab: LRGB ratio 1
Devices. Clear set to 1, Focus set to 0, Guide box all unchecked,, Focus box no autofocus

**Comment by astromiester1** [comment]
Got a workaround that made the script pass the platesolve and take images which worked. Going to try and see how the guider and focuser portion part integrate before taking the images now.. So, far very promissing.. I love this tool you made..... If you have a donation page let me know...

**Comment by rrskybox** [comment]
I'd like to hear what your work-around was.  SB changed how scripted CLS is handled during their last build and I don't remember if I went back and removed what I did in Humason to deal with the problem they fixed, but probably not yet.  As I said, I've been distracted with other projects...

Also, the Rotator tab has the Plate Solving functions on it, for obvious reasons.  If you want that tab to show, then enable a Rotator in the Options window.   You can then show the tab but disable the function on the Devices tab, if that makes sense.

**Comment by astromiester1** [comment]
Spoke too soon... Files never get saved... The workaround was to change my platesolver settings to 2x2 and double the image scale but use blind in allsky.

I noticed even though I have the save checkbox image checked in TSX once it takes images they never save anywhere I tell it to go in TSX. Your script unchecks the box so nothing gets saved. Wierd...

**Comment by astromiester1** [comment]
The workaround was to change my platesolver settings to 2x2 and double the image scale but use blind in allsky.

**Comment by rrskybox** [comment]
Hmmm... not sure why that would work, but see my comment about setting up an FOVI.
